"use client";

/* eslint-disable @next/next/no-img-element, react-hooks/exhaustive-deps */
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { getSupabaseBrowserClient } from "@/lib/supabase/client";
import { useAppDispatch, useAppState } from "@/lib/store/provider";
import { useToast } from "@/lib/toast/provider";
import type { ProductCatalogItem } from "@/lib/types";
import { PageSkeleton } from "@/components/ui/PageSkeleton";

type Product = { id:string; title:string; price_label?:string|null; image_url:string|null; purchase_url?:string|null; description:string|null; category?:string|null };
type MarketProduct = Product & { purchase_url:string; prize_image_url:string|null };
type PromoBanner = { id:string; title:string; image_url:string|null; link_url:string };
const PAGE_SIZE=20;
const DISCLOSURE="이 포스팅은 쿠팡 파트너스 활동의 일환으로, 이에 따른 일정액의 수수료를 제공받습니다.";

function ProductInfo({ product }: { product:Product }) {
  return <div className="min-w-0 flex-1"><p className="text-micro text-brand-amber">{product.category??"미분류"}</p><h4 className="line-clamp-2 text-caption font-bold">{product.title}</h4><p className="mt-1 text-caption font-bold">{product.price_label??"가격정보 없음"}</p><details className="mt-2 text-micro text-text-secondary"><summary className="cursor-pointer">더보기</summary><p className="mt-2">{product.description??"상품 설명이 없습니다."}</p></details></div>;
}

function PromotionCarousel({banners}:{banners:PromoBanner[]}){const[index,setIndex]=useState(0);const[start,setStart]=useState<number|null>(null);useEffect(()=>{if(banners.length<2)return;const timer=setInterval(()=>setIndex(current=>(current+1)%banners.length),2000);return()=>clearInterval(timer);},[banners.length]);if(!banners.length)return null;const end=(x:number)=>{if(start!==null&&Math.abs(x-start)>40)setIndex(current=>(current+(x<start?1:-1)+banners.length)%banners.length);setStart(null);};return <section className="mt-8"><h3 className="mb-3 text-subtitle">상품 이벤트 · 프로모션</h3><div onTouchStart={event=>setStart(event.touches[0].clientX)} onTouchEnd={event=>end(event.changedTouches[0].clientX)} className="max-w-sm overflow-hidden rounded-card border border-border"><div className="flex transition-transform duration-500" style={{transform:`translateX(-${index*100}%)`}}>{banners.map(banner=><a key={banner.id} href={banner.link_url} target="_blank" rel="noreferrer" className="flex aspect-square min-w-full items-center justify-center bg-surface-raised">{banner.image_url?<img src={banner.image_url} alt={banner.title} className="h-full w-full object-cover"/>:<span className="px-5 text-center text-subtitle">{banner.title}</span>}</a>)}</div></div><p className="mt-2 text-micro text-text-muted">{DISCLOSURE}</p></section>}

export default function AdminProductsPage() {
  const state=useAppState(); const dispatch=useAppDispatch(); const toast=useToast();
  const [tab,setTab]=useState<"cart"|"recommended">("cart"); const [market,setMarket]=useState<MarketProduct[]>([]); const [saved,setSaved]=useState<string[]>([]); const [query,setQuery]=useState("");
  const [loading,setLoading]=useState(true);
  const [banners,setBanners]=useState<PromoBanner[]>([]); const [page,setPage]=useState(0); const [touchStart,setTouchStart]=useState<number|null>(null);
  const [editing,setEditing]=useState<Product|null>(null); const [formOpen,setFormOpen]=useState(false); const [title,setTitle]=useState(""); const [price,setPrice]=useState(""); const [category,setCategory]=useState(""); const [description,setDescription]=useState(""); const [url,setUrl]=useState("");
  const token=async()=> (await getSupabaseBrowserClient()!.auth.getSession()).data.session?.access_token;
  const loadCatalog=async()=>{const access=await token();if(!access)return;const response=await fetch("/api/admin/products",{headers:{Authorization:`Bearer ${access}`}});const payload=await response.json();if(response.ok)dispatch({type:"SET_PRODUCT_CATALOG",products:payload.products});else toast(payload.error);};
  const loadMarket=async()=>{const access=await token();if(!access)return;const response=await fetch("/api/admin/product-market",{headers:{Authorization:`Bearer ${access}`}});const payload=await response.json();if(response.ok){setMarket(payload.products);setSaved(payload.savedIds);setBanners(payload.banners??[]);}else toast(payload.error);};
  useEffect(()=>{void Promise.all([loadCatalog(),loadMarket()]).finally(()=>setLoading(false));},[]);
  const visible=useMemo(()=>market.filter((product)=>`${product.title} ${product.category??""}`.toLowerCase().includes(query.toLowerCase())),[market,query]);
  const addToCart=async(id:string)=>{const access=await token();if(!access)return;const response=await fetch("/api/admin/product-market",{method:"POST",headers:{Authorization:`Bearer ${access}`,"Content-Type":"application/json"},body:JSON.stringify({productId:id,action:"save"})});const payload=await response.json();if(!response.ok)return toast(payload.error);setSaved((ids)=>ids.includes(id)?ids:[...ids,id]);await loadCatalog();toast("장바구니에 담았어요.");};
  const begin=(product:Product)=>{setEditing(product);setTitle(product.title);setPrice(product.price_label??"");setCategory(product.category??"");setDescription(product.description??"");setUrl(product.purchase_url??"");setFormOpen(true);};
  const reset=()=>{setEditing(null);setTitle("");setPrice("");setCategory("");setDescription("");setUrl("");setFormOpen(false);};
  const save=async()=>{if(!title.trim())return toast("상품명을 입력해 주세요.");const access=await token();if(!access)return;const response=await fetch("/api/admin/products",{method:editing?"PATCH":"POST",headers:{Authorization:`Bearer ${access}`,"Content-Type":"application/json"},body:JSON.stringify({productId:editing?.id,title,priceLabel:price,category,description,purchaseUrl:url||null,imageUrl:editing?.image_url??null})});const payload=await response.json();if(!response.ok)return toast(payload.error);await loadCatalog();reset();toast("상품을 저장했어요.");};
  const remove=async(id:string)=>{if(!confirm("장바구니에서 삭제할까요?"))return;const access=await token();if(!access)return;const response=await fetch("/api/admin/products",{method:"DELETE",headers:{Authorization:`Bearer ${access}`,"Content-Type":"application/json"},body:JSON.stringify({productId:id})});if(!response.ok)return toast("삭제하지 못했어요.");await Promise.all([loadCatalog(),loadMarket()]);};
  const cart=state.productCatalog as Array<ProductCatalogItem&{price_label?:string|null;category?:string|null}>;
  const source=tab==="cart"?cart:visible;const pageCount=Math.max(1,Math.ceil(source.length/PAGE_SIZE));const paged=source.slice(page*PAGE_SIZE,(page+1)*PAGE_SIZE);const movePage=(direction:number)=>setPage(current=>Math.max(0,Math.min(pageCount-1,current+direction)));const swipeProps={onTouchStart:(event:React.TouchEvent)=>setTouchStart(event.touches[0].clientX),onTouchEnd:(event:React.TouchEvent)=>{if(touchStart===null)return;const distance=event.changedTouches[0].clientX-touchStart;if(Math.abs(distance)>50)movePage(distance<0?1:-1);setTouchStart(null);}};
  useEffect(()=>{setPage(0);},[tab,query]);
  if(loading)return <PageSkeleton/>;
  return <div><Link href="/admin/rewards" className="text-caption text-text-secondary">이벤트/상품 관리</Link><h2 className="mt-2 text-title">상품 카탈로그</h2><p className="mb-4 mt-1 text-caption text-text-secondary">추천상품을 확인하고 장바구니에 저장해 이벤트 경품으로 사용하세요.</p><iframe title="쿠팡 파트너스 배너" src="https://coupa.ng/coeq4M" width="100%" height="36" frameBorder="0" scrolling="no" referrerPolicy="unsafe-url" className="mb-1"/><p className="mb-5 text-micro text-text-muted">{DISCLOSURE}</p><div className="mb-5 grid max-w-md grid-cols-2 rounded-xl bg-surface-raised p-1"><button onClick={()=>setTab("cart")} className={`rounded-lg px-4 py-2.5 font-bold ${tab==="cart"?"bg-brand-amber text-surface-page":"text-text-secondary"}`}>장바구니 {cart.length}</button><button onClick={()=>setTab("recommended")} className={`rounded-lg px-4 py-2.5 font-bold ${tab==="recommended"?"bg-brand-amber text-surface-page":"text-text-secondary"}`}>추천상품</button></div>
  {tab==="recommended"&&<><input value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="상품명 또는 카테고리 검색" className="mb-3 w-full rounded-xl border border-border px-4 py-3"/>{query&&visible.length===0&&<div className="mb-4 rounded-xl bg-surface-raised p-4 text-caption"><p>카탈로그에 검색 결과가 없습니다.</p><a href={`https://www.coupang.com/np/search?q=${encodeURIComponent(query)}`} target="_blank" rel="noreferrer" className="mt-2 inline-flex font-bold text-brand-amber">쿠팡 전체 상품에서 “{query}” 검색하기 →</a></div>}</>}
  <section {...swipeProps}>{source.length===0&&tab==="cart"&&<p className="rounded-xl bg-surface-page p-5 text-caption text-text-secondary">장바구니가 비어 있습니다.</p>}<div className="grid grid-cols-2 gap-2 sm:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5">{paged.map((product)=><article key={product.id} className="overflow-hidden rounded-xl border border-border bg-surface-page"><img src={product.image_url??"/images/placeholder-product.svg"} alt={product.title} className="aspect-square w-full object-cover"/><div className="p-2.5"><ProductInfo product={product}/><div className="mt-3 grid gap-1.5">{product.purchase_url&&<a href={product.purchase_url} target="_blank" rel="noreferrer" className="rounded-lg border border-border px-2 py-2 text-center text-micro font-bold">구매하기</a>}{tab==="recommended"?<button disabled={saved.includes(product.id)} onClick={()=>void addToCart(product.id)} className="rounded-lg bg-brand-amber px-2 py-2 text-micro font-bold text-surface-page disabled:opacity-50">{saved.includes(product.id)?"담김":"장바구니 담기"}</button>:<button onClick={()=>void remove(product.id)} className="rounded-lg px-2 py-1 text-micro text-state-danger">삭제</button>}</div></div></article>)}</div>{pageCount>1&&<div className="mt-4 flex items-center justify-center gap-3"><button disabled={page===0} onClick={()=>movePage(-1)} className="rounded-lg border border-border px-3 py-2 disabled:opacity-30">‹</button><span className="text-caption">{page+1} / {pageCount}</span><button disabled={page===pageCount-1} onClick={()=>movePage(1)} className="rounded-lg border border-border px-3 py-2 disabled:opacity-30">›</button></div>}{tab==="cart"&&<button onClick={()=>setFormOpen(true)} className="mt-4 text-micro underline">+ 상품 직접 등록</button>}</section>
  <PromotionCarousel banners={banners}/>
  {formOpen&&tab==="cart"&&<section className="mt-5 rounded-card bg-surface-page p-5"><h3 className="mb-3 text-subtitle">{editing?"상품 수정":"상품 직접 등록"}</h3><div className="grid gap-3 sm:grid-cols-2"><input value={title} onChange={(e)=>setTitle(e.target.value)} placeholder="상품명" className="rounded-lg border border-border px-3 py-2"/><input value={price} onChange={(e)=>setPrice(e.target.value)} placeholder="가격" className="rounded-lg border border-border px-3 py-2"/><input value={category} onChange={(e)=>setCategory(e.target.value)} placeholder="카테고리" className="rounded-lg border border-border px-3 py-2"/><input value={url} onChange={(e)=>setUrl(e.target.value)} placeholder="구매 링크" className="rounded-lg border border-border px-3 py-2"/><textarea value={description} onChange={(e)=>setDescription(e.target.value)} placeholder="상품 설명" className="rounded-lg border border-border px-3 py-2 sm:col-span-2"/></div><div className="mt-4 flex gap-2"><button onClick={()=>void save()} className="rounded-lg bg-brand-amber px-4 py-2 font-bold text-surface-page">저장</button><button onClick={reset} className="rounded-lg border border-border px-4 py-2">취소</button></div></section>}
  </div>;
}
