"use client";
/* eslint-disable @next/next/no-img-element, react-hooks/exhaustive-deps */
import Link from "next/link";
import { useEffect, useState } from "react";
import { Button } from "@/components/ui/Button";
import { useToast } from "@/lib/toast/provider";
import { getSupabaseBrowserClient } from "@/lib/supabase/client";
import { useAppDispatch, useAppState } from "@/lib/store/provider";
import type { ProductCatalogItem } from "@/lib/types";

async function imageData(file: File) { return await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result as string);reader.onerror=reject;reader.readAsDataURL(file);}); }

export default function AdminProductsPage() {
  const state=useAppState(); const dispatch=useAppDispatch(); const toast=useToast();
  const [editing,setEditing]=useState<ProductCatalogItem|null>(null); const [title,setTitle]=useState(""); const [description,setDescription]=useState(""); const [purchaseUrl,setPurchaseUrl]=useState(""); const [imageUrl,setImageUrl]=useState<string|null>(null); const [saving,setSaving]=useState(false);
  const accessToken=async()=>{const client=getSupabaseBrowserClient();const {data}=await client!.auth.getSession();return data.session?.access_token;};
  const load=async()=>{const access=await accessToken();if(!access)return;const response=await fetch("/api/admin/products",{headers:{Authorization:`Bearer ${access}`}});const payload=await response.json();if(response.ok)dispatch({type:"SET_PRODUCT_CATALOG",products:payload.products});else toast(payload.error??"상품을 불러오지 못했어요.");};
  useEffect(()=>{void load();},[]);
  const reset=()=>{setEditing(null);setTitle("");setDescription("");setPurchaseUrl("");setImageUrl(null);};
  const begin=(product:ProductCatalogItem)=>{setEditing(product);setTitle(product.title);setDescription(product.description??"");setPurchaseUrl(product.purchase_url??"");setImageUrl(product.image_url);window.scrollTo({top:0,behavior:"smooth"});};
  const save=async()=>{if(!title.trim()){toast("상품명을 입력해 주세요.");return;}const url=purchaseUrl.trim()||null;if(url&&!/^https?:\/\//i.test(url)){toast("구매 링크는 http:// 또는 https://로 시작해야 해요.");return;}setSaving(true);try{const access=await accessToken();if(!access)throw new Error("로그인이 필요합니다.");const response=await fetch("/api/admin/products",{method:editing?"PATCH":"POST",headers:{Authorization:`Bearer ${access}`,"Content-Type":"application/json"},body:JSON.stringify({productId:editing?.id,title:title.trim(),description:description.trim()||null,purchaseUrl:url,imageUrl})});const payload=await response.json();if(!response.ok)throw new Error(payload.error);await load();toast(editing?"상품을 수정했어요.":"상품을 추가했어요.");reset();}catch(error){toast(error instanceof Error?error.message:"상품을 저장하지 못했어요.");}finally{setSaving(false);}};
  const remove=async(productId:string)=>{const access=await accessToken();if(!access)return;const response=await fetch("/api/admin/products",{method:"DELETE",headers:{Authorization:`Bearer ${access}`,"Content-Type":"application/json"},body:JSON.stringify({productId})});const payload=await response.json();if(!response.ok){toast(payload.error??"상품을 삭제하지 못했어요.");return;}await load();toast("상품을 삭제했어요.");};
  return <div><Link href="/admin/rewards" className="text-caption text-text-secondary">← 이벤트/상품 관리</Link><h2 className="mt-2 text-title">상품 보관함</h2><p className="mb-5 mt-1 text-caption text-text-secondary">이벤트에 사용할 상품과 구매 링크를 미리 관리하세요.</p>
    <section className="mb-6 rounded-card bg-surface-page p-5"><h3 className="mb-3 text-subtitle">{editing?"상품 수정":"새 상품 등록"}</h3><div className="grid gap-3 sm:grid-cols-2"><label className="text-caption text-text-secondary">상품명<input value={title} onChange={e=>setTitle(e.target.value)} className="mt-1 w-full rounded-lg border border-border px-3 py-2"/></label><label className="text-caption text-text-secondary">구매 링크<input type="url" value={purchaseUrl} onChange={e=>setPurchaseUrl(e.target.value)} placeholder="https://..." className="mt-1 w-full rounded-lg border border-border px-3 py-2"/></label><label className="text-caption text-text-secondary sm:col-span-2">상품 설명<input value={description} onChange={e=>setDescription(e.target.value)} className="mt-1 w-full rounded-lg border border-border px-3 py-2"/></label><div className="sm:col-span-2"><p className="mb-1 text-caption text-text-secondary">상품 이미지</p><div className="flex items-center gap-3">{imageUrl?<img src={imageUrl} alt="상품 미리보기" className="h-16 w-16 rounded-lg object-cover"/>:<div className="h-16 w-16 rounded-lg border border-dashed border-border"/>}<label className="cursor-pointer text-caption text-brand-amber">이미지 선택<input type="file" accept="image/*" className="hidden" onChange={async e=>{const file=e.target.files?.[0];if(file)setImageUrl(await imageData(file));}}/></label>{imageUrl&&<button className="text-caption text-state-danger" onClick={()=>setImageUrl(null)}>제거</button>}</div></div></div><div className="mt-4 flex gap-2"><Button onClick={save} disabled={saving}>{saving?"저장 중...":editing?"수정 저장":"상품 추가"}</Button>{editing&&<Button variant="secondary" onClick={reset}>취소</Button>}</div></section>
    <section><h3 className="mb-3 text-subtitle">등록 상품 {state.productCatalog.length}개</h3><div className="grid gap-3 lg:grid-cols-3">{state.productCatalog.length===0&&<p className="rounded-xl bg-surface-page p-5 text-caption text-text-secondary lg:col-span-3">등록된 상품이 없습니다.</p>}{state.productCatalog.map(product=><article key={product.id} className="rounded-xl border border-border bg-surface-page p-4"><div className="flex gap-3">{product.image_url?<img src={product.image_url} alt={product.title} className="h-16 w-16 rounded-lg object-cover"/>:<div className="h-16 w-16 rounded-lg bg-surface-card"/>}<div className="min-w-0 flex-1"><h4 className="font-bold">{product.title}</h4><p className="mt-1 text-caption text-text-secondary">{product.description||"설명 없음"}</p></div></div><div className="mt-4 flex flex-wrap gap-2">{product.purchase_url&&<a href={product.purchase_url} target="_blank" rel="noreferrer" className="rounded-lg bg-brand-amber px-3 py-2 text-caption font-bold text-surface-page">구매 바로가기</a>}<button onClick={()=>begin(product)} className="rounded-lg border border-border px-3 py-2 text-caption">수정</button><button onClick={()=>void remove(product.id)} className="px-2 py-2 text-caption text-state-danger">삭제</button></div></article>)}</div></section>
  </div>;
}
