"use client";
import Link from "next/link";
import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import { getAuthEmailForIdentifier } from "@/lib/auth/identifier";
import { getSupabaseBrowserClient } from "@/lib/supabase/client";

export default function SellerLoginPage(){const router=useRouter();const [identifier,setIdentifier]=useState("");const [password,setPassword]=useState("");const [message,setMessage]=useState("");const [submitting,setSubmitting]=useState(false);
 async function submit(event:FormEvent){event.preventDefault();setSubmitting(true);setMessage("");const client=getSupabaseBrowserClient();if(!client){setMessage("로그인 설정을 확인해 주세요.");setSubmitting(false);return;}const signIn=await client.auth.signInWithPassword({email:getAuthEmailForIdentifier(identifier),password});if(signIn.error){setMessage("아이디 또는 비밀번호를 확인해 주세요.");setSubmitting(false);return;}const check=await fetch("/api/seller/products",{headers:{Authorization:`Bearer ${signIn.data.session.access_token}`}});if(!check.ok){await client.auth.signOut();const payload=await check.json();setMessage(payload.error??"판매자 권한이 없는 계정입니다.");setSubmitting(false);return;}router.push("/seller/products");}
 return <main className="mx-auto flex min-h-screen max-w-app items-center px-6 py-10"><div className="w-full"><Link href="/" className="text-caption text-text-secondary">&lt; 일반 로그인</Link><div className="mt-5 rounded-card bg-surface-card p-5"><p className="text-caption font-bold text-brand-amber">DEVELOPER / SELLER</p><h1 className="mt-1 text-title">개발자·판매자 로그인</h1><p className="mt-2 text-caption text-text-secondary">추천 상품 카탈로그를 관리하는 전용 화면입니다.</p><form onSubmit={submit} className="mt-5 space-y-3"><label className="block text-caption text-text-secondary">한글 아이디 또는 이메일<input required value={identifier} onChange={e=>setIdentifier(e.target.value)} className="mt-1 w-full rounded-xl bg-surface-raised px-3 py-2.5 text-text-primary outline-none"/></label><label className="block text-caption text-text-secondary">비밀번호<input required minLength={6} type="password" value={password} onChange={e=>setPassword(e.target.value)} className="mt-1 w-full rounded-xl bg-surface-raised px-3 py-2.5 text-text-primary outline-none"/></label>{message&&<p className="text-caption text-state-danger">{message}</p>}<button disabled={submitting} className="w-full rounded-xl bg-brand-amber py-3 font-bold text-surface-page disabled:opacity-60">{submitting?"확인 중...":"전용 화면 로그인"}</button></form></div></div></main>}
