"use client";

/* eslint-disable @next/next/no-img-element, react-hooks/exhaustive-deps */
import { ChangeEvent, useEffect, useMemo, useState } from "react";
import { getSupabaseBrowserClient } from "@/lib/supabase/client";
import { useToast } from "@/lib/toast/provider";

type Product = { id:string; title:string; price_label:string|null; image_url:string|null; prize_image_url:string|null; purchase_url:string; description:string|null; category:string|null; is_active:boolean; sort_order:number };
type FormState = { title:string; priceLabel:string; imageUrl:string; prizeImageUrl:string; purchaseUrl:string; description:string; category:string; isActive:boolean; sortOrder:number };
const EMPTY: FormState = { title:"", priceLabel:"", imageUrl:"", prizeImageUrl:"", purchaseUrl:"", description:"", category:"문구", isActive:true, sortOrder:0 };
const DEFAULT_CATEGORIES = ["문구", "간식", "미용", "의류", "잡화", "상품권", "기타"];

function ImagePicker({ title, value, disabled, onChange }: { title:string; value:string; disabled?:boolean; onChange:(value:string)=>void }) {
  const choose = (event: ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    event.target.value = "";
    if (!file) return;
    const reader = new FileReader();
    reader.onload = () => onChange(String(reader.result));
    reader.readAsDataURL(file);
  };
  return <div className={`rounded-xl bg-surface-card p-4 ${disabled ? "opacity-60" : ""}`}><p className="text-caption font-bold">{title}</p><div className="mt-3 flex items-center gap-3">{value ? <img src={value} alt={title} className="h-24 w-24 rounded-xl object-cover" /> : <div className="flex h-24 w-24 items-center justify-center rounded-xl border border-dashed border-border text-caption text-text-muted">이미지 없음</div>}<label className={`rounded-lg border border-border px-3 py-2 text-caption font-bold ${disabled ? "pointer-events-none" : "cursor-pointer"}`}>이미지 등록<input type="file" accept="image/*" className="hidden" onChange={choose} /></label>{value && !disabled && <button type="button" className="text-caption text-state-danger" onClick={() => onChange("")}>삭제</button>}</div></div>;
}

export default function DeveloperProductsPage() {
  const toast = useToast();
  const [tab, setTab] = useState<"new"|"sourcing">("new");
  const [view, setView] = useState<"card"|"list">("card");
  const [products, setProducts] = useState<Product[]>([]);
  const [editing, setEditing] = useState<Product|null>(null);
  const [form, setForm] = useState<FormState>(EMPTY);
  const [samePrizeImage, setSamePrizeImage] = useState(true);
  const [previewing, setPreviewing] = useState(false);
  const [customCategories, setCustomCategories] = useState<string[]>([]);
  const [newCategory, setNewCategory] = useState("");
  const [error, setError] = useState("");
  const categories = useMemo(() => Array.from(new Set([...DEFAULT_CATEGORIES, ...products.map((p) => p.category).filter((v):v is string => Boolean(v)), ...customCategories])), [products, customCategories]);
  const token = async () => (await getSupabaseBrowserClient()!.auth.getSession()).data.session?.access_token;
  const load = async () => { const access = await token(); if (!access) return setError("먼저 개발자 계정으로 로그인해 주세요."); const response = await fetch("/api/seller/products", { headers:{ Authorization:`Bearer ${access}` } }); const payload = await response.json(); if (!response.ok) return setError(payload.error); setProducts(payload.products); setError(""); };
  useEffect(() => { void load(); }, []);
  const reset = () => { setEditing(null); setForm(EMPTY); setSamePrizeImage(true); };
  const edit = (product: Product) => { setEditing(product); setForm({ title:product.title, priceLabel:product.price_label??"", imageUrl:product.image_url??"", prizeImageUrl:product.prize_image_url??"", purchaseUrl:product.purchase_url, description:product.description??"", category:product.category??"기타", isActive:product.is_active, sortOrder:product.sort_order }); setSamePrizeImage(Boolean(product.image_url) && product.image_url === product.prize_image_url); setTab("new"); };
  const fetchPreview = async () => { if (!/^https?:\/\//i.test(form.purchaseUrl)) return toast("올바른 상품 링크를 먼저 입력해 주세요."); const access=await token(); if(!access)return; setPreviewing(true); try { const response=await fetch("/api/seller/link-preview",{method:"POST",headers:{Authorization:`Bearer ${access}`,"Content-Type":"application/json"},body:JSON.stringify({url:form.purchaseUrl})}); const payload=await response.json(); if(!response.ok)throw new Error(payload.error); setForm((current)=>({...current,title:current.title||payload.title||"",priceLabel:current.priceLabel||payload.priceLabel||"",description:current.description||payload.description||"",imageUrl:payload.imageUrl||current.imageUrl})); toast(payload.imageUrl?"썸네일을 구매 상품 이미지로 등록했어요.":"대표 이미지가 없어 직접 등록해 주세요."); } catch(e){toast(e instanceof Error?e.message:"상품 정보를 불러오지 못했어요.");} finally{setPreviewing(false);} };
  const save = async () => { if(!form.title.trim() || !/^https?:\/\//i.test(form.purchaseUrl)) return toast("상품명과 올바른 구매 링크를 입력해 주세요."); const access=await token(); if(!access)return; const body={...form,prizeImageUrl:samePrizeImage?form.imageUrl:form.prizeImageUrl,productId:editing?.id}; const response=await fetch("/api/seller/products",{method:editing?"PATCH":"POST",headers:{Authorization:`Bearer ${access}`,"Content-Type":"application/json"},body:JSON.stringify(body)}); const payload=await response.json(); if(!response.ok)return toast(payload.error??"저장하지 못했어요."); toast(editing?"상품을 수정했어요.":"추천 상품을 등록했어요."); reset(); await load(); setTab("sourcing"); };
  const remove = async (id:string) => { if(!confirm("이 상품을 삭제할까요?"))return; const access=await token(); if(!access)return; const response=await fetch("/api/seller/products",{method:"DELETE",headers:{Authorization:`Bearer ${access}`,"Content-Type":"application/json"},body:JSON.stringify({productId:id})}); if(!response.ok)return toast("삭제하지 못했어요."); await load(); };
  const addCategory=()=>{const value=newCategory.trim();if(!value)return;setCustomCategories((items)=>items.includes(value)?items:[...items,value]);setForm((current)=>({...current,category:value}));setNewCategory("");};

  return <main className="min-h-screen bg-surface-card p-6 text-text-primary"><div className="mx-auto max-w-6xl"><h1 className="text-title">StickerUp 개발자 상품 관리</h1><p className="mt-1 text-caption text-text-secondary">구매 상품과 이벤트 경품 이미지를 구분해 관리합니다.</p>
    <div className="mt-6 grid max-w-md grid-cols-2 rounded-xl bg-surface-page p-1"><button onClick={()=>setTab("new")} className={`rounded-lg px-4 py-3 font-bold ${tab==="new"?"bg-brand-amber text-surface-page":"text-text-secondary"}`}>새 추천상품</button><button onClick={()=>setTab("sourcing")} className={`rounded-lg px-4 py-3 font-bold ${tab==="sourcing"?"bg-brand-amber text-surface-page":"text-text-secondary"}`}>소싱상품 {products.length}</button></div>
    {error ? <div className="mt-6 rounded-card border border-state-danger p-5 text-state-danger">{error}</div> : tab==="new" ? <section className="mt-5 rounded-card bg-surface-page p-5"><h2 className="mb-4 text-subtitle">{editing?"추천상품 수정":"새 추천상품"}</h2><div className="grid gap-4 md:grid-cols-2">
      <label className="text-caption text-text-secondary md:col-span-2">상품 링크<div className="mt-1 flex gap-2"><input value={form.purchaseUrl} onChange={(e)=>setForm({...form,purchaseUrl:e.target.value})} className="min-w-0 flex-1 rounded-lg border border-border px-3 py-2" placeholder="https://..."/><button type="button" disabled={previewing} onClick={()=>void fetchPreview()} className="rounded-lg border border-brand-amber px-4 py-2 font-bold text-brand-amber">{previewing?"불러오는 중":"썸네일 불러오기"}</button></div></label>
      <label className="text-caption text-text-secondary">상품명<input value={form.title} onChange={(e)=>setForm({...form,title:e.target.value})} className="mt-1 w-full rounded-lg border border-border px-3 py-2"/></label><label className="text-caption text-text-secondary">가격<input value={form.priceLabel} onChange={(e)=>setForm({...form,priceLabel:e.target.value})} className="mt-1 w-full rounded-lg border border-border px-3 py-2" placeholder="예: 12,900원"/></label>
      <label className="text-caption text-text-secondary">카테고리<select value={form.category} onChange={(e)=>setForm({...form,category:e.target.value})} className="mt-1 w-full rounded-lg border border-border px-3 py-2">{categories.map((category)=><option key={category}>{category}</option>)}</select></label><div className="flex items-end gap-2"><input value={newCategory} onChange={(e)=>setNewCategory(e.target.value)} className="min-w-0 flex-1 rounded-lg border border-border px-3 py-2" placeholder="새 카테고리"/><button type="button" onClick={addCategory} className="rounded-lg border border-border px-3 py-2">추가</button></div>
      <ImagePicker title="구매 상품 이미지 (썸네일)" value={form.imageUrl} onChange={(imageUrl)=>setForm({...form,imageUrl})}/><div><label className="mb-2 flex items-center gap-2 text-caption font-bold"><input type="checkbox" checked={samePrizeImage} onChange={(e)=>setSamePrizeImage(e.target.checked)}/>경품도 구매 상품 이미지와 동일하게 사용</label><ImagePicker title="이벤트 경품 이미지" value={samePrizeImage?form.imageUrl:form.prizeImageUrl} disabled={samePrizeImage} onChange={(prizeImageUrl)=>setForm({...form,prizeImageUrl})}/></div>
      <label className="text-caption text-text-secondary md:col-span-2">상품 설명<textarea value={form.description} onChange={(e)=>setForm({...form,description:e.target.value})} className="mt-1 min-h-24 w-full rounded-lg border border-border px-3 py-2"/></label></div><div className="mt-4 flex gap-2"><button onClick={()=>void save()} className="rounded-lg bg-brand-amber px-4 py-2 font-bold text-surface-page">{editing?"수정 저장":"상품 등록"}</button>{editing&&<button onClick={reset} className="rounded-lg border border-border px-4 py-2">취소</button>}</div></section> :
      <section className="mt-5"><div className="mb-3 flex items-center justify-between"><h2 className="text-subtitle">소싱상품</h2><div className="flex rounded-lg bg-surface-page p-1"><button onClick={()=>setView("list")} className={`rounded-md px-3 py-2 text-caption ${view==="list"?"bg-brand-amber text-surface-page":""}`}>목록형</button><button onClick={()=>setView("card")} className={`rounded-md px-3 py-2 text-caption ${view==="card"?"bg-brand-amber text-surface-page":""}`}>카드형</button></div></div><div className={view==="card"?"grid gap-3 md:grid-cols-2 xl:grid-cols-3":"space-y-2"}>{products.map((product)=><article key={product.id} className={`rounded-card bg-surface-page p-4 ${view==="list"?"flex items-center gap-4":""}`}><img src={product.image_url??product.prize_image_url??"/images/placeholder-product.svg"} alt={product.title} className={view==="list"?"h-20 w-20 rounded-lg object-cover":"h-40 w-full rounded-xl object-cover"}/><div className="min-w-0 flex-1"><p className="mt-2 text-caption text-brand-amber">{product.category??"미분류"}</p><h3 className="font-bold">{product.title}</h3><p className="font-bold">{product.price_label??"가격정보 없음"}</p><details className="mt-2 text-caption text-text-secondary"><summary className="cursor-pointer">더보기</summary><p className="mt-2">{product.description??"상품 설명이 없습니다."}</p></details></div><div className={`flex gap-2 ${view==="card"?"mt-3":"ml-auto"}`}><a href={product.purchase_url} target="_blank" rel="noreferrer" className="rounded-lg border border-border px-3 py-2 text-caption">구매하기</a><button onClick={()=>edit(product)} className="rounded-lg border border-border px-3 py-2 text-caption">수정</button><button onClick={()=>void remove(product.id)} className="px-2 py-2 text-caption text-state-danger">삭제</button></div></article>)}</div></section>}
  </div></main>;
}
