"use client";
/* eslint-disable @next/next/no-img-element, react-hooks/exhaustive-deps */
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { getSupabaseBrowserClient } from "@/lib/supabase/client";
import { useToast } from "@/lib/toast/provider";

type MarketProduct = { id:string; title:string; image_url:string|null; purchase_url:string; description:string|null; category:string|null };

export default function ProductMarketPage() {
  const toast=useToast(); const [products,setProducts]=useState<MarketProduct[]>([]); const [favorites,setFavorites]=useState<string[]>([]); const [saved,setSaved]=useState<string[]>([]); const [query,setQuery]=useState(""); const [onlyFavorites,setOnlyFavorites]=useState(false);
  const token=async()=>{const client=getSupabaseBrowserClient();const {data}=await client!.auth.getSession();return data.session?.access_token;};
  const load=async()=>{const access=await token();if(!access)return;const response=await fetch("/api/admin/product-market",{headers:{Authorization:`Bearer ${access}`}});const payload=await response.json();if(!response.ok){toast(payload.error??"추천 상품을 불러오지 못했어요.");return;}setProducts(payload.products);setFavorites(payload.favoriteIds);setSaved(payload.savedIds);};
  useEffect(()=>{void load();},[]);
  const action=async(productId:string,action:"favorite"|"save")=>{const access=await token();if(!access)return;const response=await fetch("/api/admin/product-market",{method:"POST",headers:{Authorization:`Bearer ${access}`,"Content-Type":"application/json"},body:JSON.stringify({productId,action})});const payload=await response.json();if(!response.ok){toast(payload.error??"처리하지 못했어요.");return;}if(action==="favorite")setFavorites(current=>payload.favorite?[...current,productId]:current.filter(id=>id!==productId));else{setSaved(current=>current.includes(productId)?current:[...current,productId]);toast("내 상품 카탈로그에 저장했어요.");}};
  const visible=useMemo(()=>products.filter(product=>(!onlyFavorites||favorites.includes(product.id))&&(`${product.title} ${product.description??""} ${product.category??""}`).toLowerCase().includes(query.toLowerCase())),[products,favorites,onlyFavorites,query]);
  return <div><div className="flex flex-wrap items-end justify-between gap-3"><div><h2 className="text-title">추천 상품 둘러보기</h2><p className="mt-1 text-caption text-text-secondary">마음에 드는 상품을 저장하면 이벤트 경품으로 바로 사용할 수 있어요.</p></div><Link href="/admin/products" className="rounded-xl border border-border bg-surface-card px-4 py-2.5 text-body font-bold">상품 카탈로그 →</Link></div>
    <div className="my-5 flex gap-2"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="상품명, 설명, 카테고리 검색" className="min-w-0 flex-1 rounded-xl border border-border px-4 py-3"/><button onClick={()=>setOnlyFavorites(v=>!v)} className={`rounded-xl border px-4 py-2 font-bold ${onlyFavorites?"border-brand-amber bg-brand-amber text-surface-page":"border-border bg-surface-card"}`}>♥ 찜한 상품</button></div>
    <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{visible.map(product=><article key={product.id} className="overflow-hidden rounded-card border border-border bg-surface-page">{product.image_url?<img src={product.image_url} alt={product.title} className="h-44 w-full object-cover"/>:<div className="flex h-44 items-center justify-center bg-surface-card text-text-muted">상품 이미지</div>}<div className="p-4"><div className="flex items-start justify-between gap-2"><div>{product.category&&<p className="mb-1 text-caption text-brand-amber">{product.category}</p>}<h3 className="font-bold">{product.title}</h3></div><button aria-label="찜하기" onClick={()=>void action(product.id,"favorite")} className={`text-2xl ${favorites.includes(product.id)?"text-state-danger":"text-text-muted"}`}>{favorites.includes(product.id)?"♥":"♡"}</button></div><p className="mt-2 min-h-10 text-caption text-text-secondary">{product.description??"상품 설명이 없습니다."}</p><div className="mt-4 flex gap-2"><a href={product.purchase_url} target="_blank" rel="noreferrer" className="flex-1 rounded-lg border border-border px-3 py-2 text-center text-caption font-bold">상품 보기</a><button disabled={saved.includes(product.id)} onClick={()=>void action(product.id,"save")} className="flex-1 rounded-lg bg-brand-amber px-3 py-2 text-caption font-bold text-surface-page disabled:opacity-50">{saved.includes(product.id)?"저장됨":"보관함에 저장"}</button></div></div></article>)}{visible.length===0&&<p className="rounded-card bg-surface-page p-6 text-caption text-text-secondary">조건에 맞는 추천 상품이 없습니다.</p>}</div>
  </div>;
}
